n = input('Digite algo: ')
num = n.isnumeric()
al = n.isalpha()
aln = n.isalnum()
up = n.isupper()
sl = n.islower()
sp = n.isspace()
print('Ele é numérico? {} \nEle é alfabético? {} \nEle é alfanumérico?{} \nEstá somente com letra maiúscula? {}'.format(num,al,aln,up))
print('Está somente com letra minúscula? {} \nEstá somente com espaço? {}'.format(sl,sp))